# Generated by Django 5.0.1 on 2024-02-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_user_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelPack",
            fields=[
                ("levelPackId", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LevelType",
            fields=[
                ("levelTypeId", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="stars",
            new_name="starNum",
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("levelId", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("difficulty", models.IntegerField()),
                ("prompt", models.TextField()),
                ("answerNum", models.IntegerField()),
                ("imageId", models.TextField()),
                ("audio", models.CharField(max_length=50)),
                ("allotedTime", models.IntegerField()),
                ("rightAnswer", models.TextField()),
                (
                    "levelPackId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.levelpack",
                    ),
                ),
                (
                    "LevelTypeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.leveltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayHistory",
            fields=[
                (
                    "passResultId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("timeStamp", models.DateTimeField()),
                ("completionTime", models.IntegerField()),
                ("correctGuess", models.BooleanField()),
                ("incorrectGuess", models.BooleanField()),
                (
                    "levelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.level"
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stars",
            fields=[
                ("trackId", models.IntegerField(primary_key=True, serialize=False)),
                ("received", models.IntegerField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WrongAnswer",
            fields=[
                (
                    "WrongAnswerId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("answer", models.TextField()),
                (
                    "levelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.level"
                    ),
                ),
            ],
        ),
    ]
