# Generated by Django 5.0.1 on 2024-02-02 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_levelpack_leveltype_rename_stars_user_starnum_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelImage",
            fields=[
                (
                    "levelImageId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("path", models.CharField(max_length=50)),
                ("imageName", models.CharField(max_length=50)),
                ("extension", models.CharField(max_length=50)),
                (
                    "levelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.level"
                    ),
                ),
            ],
        ),
    ]
