# Generated by Django 5.0.1 on 2024-02-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_levelimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="leveltype",
            name="name",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="level",
            name="levelId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="levelimage",
            name="levelImageId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="levelpack",
            name="levelPackId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="leveltype",
            name="levelTypeId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="playhistory",
            name="passResultId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="stars",
            name="trackId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="wronganswer",
            name="WrongAnswerId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
